"""rename User.otc to User.otp

Revision ID: 0640737a2661
Revises: f437d2e2aa8f
Create Date: 2019-02-02 08:11:14.147945

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0640737a2661'
down_revision = 'f437d2e2aa8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users', sa.Column('otp', sa.String(length=128), nullable=True)
    )
    op.drop_column('users', 'otc')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column(
            'otc', sa.VARCHAR(length=128), autoincrement=False, nullable=True
        )
    )
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
