"""Add telegram_id, password and one_time_code (otc) to User

Revision ID: 293926327c16
Revises:
Create Date: 2019-01-24 22:04:22.824805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293926327c16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'is_deleted',
                    existing_type=sa.BOOLEAN(),
                    nullable=False)
    op.add_column('users', sa.Column('otc', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('password', sa.String(length=60), nullable=True))
    op.add_column('users', sa.Column('telegram_id',
                                     sa.String(length=60),
                                     nullable=False,
                                     server_default="telegram_id"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_id')
    op.drop_column('users', 'password')
    op.drop_column('users', 'otc')
    op.alter_column('categories', 'is_deleted',
                    existing_type=sa.BOOLEAN(),
                    nullable=True)
    # ### end Alembic commands ###
