"""Add date of creation for Account

Revision ID: faa09e50a250
Revises: 0640737a2661
Create Date: 2019-02-08 20:18:45.579349

"""
import datetime

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa09e50a250'
down_revision = '0640737a2661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts',
                  sa.Column('creation_date',
                            sa.Date(),
                            server_default=str(datetime.date.today()),
                            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'creation_date')
    # ### end Alembic commands ###
